AWSTemplateFormatVersion: "2010-09-09"
  Description: ECR repo for Calculator App
  Resources:
    AWSCalculatorRepo:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: "awscalculator"
  Outputs:
    AWSCalculatorArn:
      Value: !GetAtt AWSCalculatorRepo.Arn
      Export:
        Name: AWSCalculatorRepoArn
